version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: studycards
    ports:
      - "5432:5432"
  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: DB_URL=postgresql://postgres:mysecretpassword@db:5432/studycards?schema=studycards&sslmode=prefer
    ports:
      - "80:4444"